[package]
name = "register-machines"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "reference"
path = "src/reference_solution.rs"

[dependencies]
rug = "1.14.0"